### PR TITLE
Added favicon, web manifest & og image

### LINKED ISSUE #30: Add favicon
See more context here at https://github.com/ml5js/ml5-website-v02-docsify/issues/157

cc @MOQN @alanvww

### PR DESCRIPTION
**Pull request by alanvww**
Fixed #30 
@QuinnHe @MOQN

### CODE REVIEW

**Comment by QuinnHe** [comment]
Thanks @alanvww ! Merged. @MOQN

**Comment by alanvww** [comment]
> Thanks @alanvww ! Moon @MOQN , seems I don't have access to this repo. Maybe you can merge it :)

I found a new issue with my implement of the metadata tag. Fixing it now.

**Comment by alanvww** [comment]
Issue fixed! Ready to merge :D @MOQN

**Comment by MOQN** [comment]
Thank you @alanvww!

**Comment by MOQN** [comment]
@QuinnHe @alanvww, I've updated your role in this repo!

**Comment by MOQN** [comment]
@alanvww updated images with rounded corners will be sent shortly!

**Pull request merged**
