### PR TITLE
About Page Updates

### PR DESCRIPTION
**Pull request by shiffman**
This is a branch to work on updates to the about page, see #11. Some things to do off the top of my head:

* [ ] Update language around "what is ml5.js", explain ml5.js next-gen and earlier version and where to find archived materials.
* [ ] Since the documentation is new and doesn't necessarily reflect all of what we hope to include about data, models, and ethical use, the language should be updated to be more clear about our aspirations and current documentation.
* [ ] Update language to explain and provide links to details about Code of Conduct and License.  cc @LiyanIbrahim
* [x] Include credits for new website and keep credits for previous website.
* [x] Update support from ITP/IMA, IMA Shanghai, DAIL (?), and past support from Google
* [x] Link to all contributors? cc @ziyuan-linn 

A quick list of updates that we need to do!

### CODE REVIEW

**Comment by gohai** [comment]
It'd be fantastic if we could acknowledge the DAIL grant - language could be something like: _Development was supported in parts by a grant by the Shanghai Frontiers Science Center of Artificial Intelligence and Deep Learning._

**Comment by MOQN** [comment]
Thank you @gohai for reminding us! I will make sure to include the text!

**Comment by shiffman** [comment]
I'm slowly updating this page piecemeal. @MOQN could you add any key website credits and @ziyuan-linn could you add generic language about library contributors with a link to all contributors? See the placeholders with `[` and `]` I've put in for now. I can edit and synthesize!

@gohai please check the language about DAIL and anything related to NYU Shanghai!

**Comment by gohai** [comment]
Perfect - thanks @shiffman!

**Comment by ziyuan-linn** [comment]
@shiffman It seems like I don't have write access to this repo. I will paste the change here since it is not too long.

The first paragraph in Acknowledgment:
```html
<p>
  ml5.js is supported by the time and dedication of open source developers from all over the
  world. We are artists, designers, technologists, researchers, educators, students,
  scientists, developers, parents, children, and everything in-between. We are proud of our{' '}
  <a href="https://github.com/ml5js/ml5-next-gen?tab=readme-ov-file#contributors-" target="_blank">
    growing list of contributors
  </a>
  .
</p>
```

**Comment by MOQN** [comment]
I will merge what we have for now!

**Comment by MOQN** [comment]
@shiffman, I apologize for closing this PR! I thought I might be able to reopen it after merging it. Is there any preferred way to reorganize this PR?

**Comment by shiffman** [comment]
> @shiffman, I apologize for closing this PR! I thought I might be able to reopen it after merging it. Is there any preferred way to reorganize this PR?

Not to worry, we can continue further updates to the about page in other branches and PRs!

**Pull request merged**
